let doctors = [
  {
    doctorId: "doc00-1",
    doctorName: "Dr. Aarav",
    speciality: "Cardiology",
    noOfYearsExperience: 12,
    imgUrl: "/images/doc1.png",
  },
  {
    doctorId: "doc00-2",
    doctorName: "Dr. Aashika",
    speciality: "Neurology",
    noOfYearsExperience: 7,
    imgUrl: "/images/doc2.webp",
  },
  {
    doctorId: "doc00-3",
    doctorName: "Dr. Aniket",
    speciality: "Pediatrics",
    noOfYearsExperience: 8,
    imgUrl: "/images/doc3.jpg",
  },
  {
    doctorId: "doc00-4",
    doctorName: "Dr. Binita",
    speciality: "Orthopedics",
    noOfYearsExperience: 5,
    imgUrl: "/images/doc4.jpg",
  },
  {
    doctorId: "doc00-5",
    doctorName: "Dr. Dipesh",
    speciality: "Dermatology",
    noOfYearsExperience: 11,
    imgUrl: "/images/doc5.jpg",
  },
  {
    doctorId: "doc00-6",
    doctorName: "Dr. Esha",
    speciality: "Psychiatry",
    noOfYearsExperience: 15,
    imgUrl: "/images/doc6.jpg",
  },
  {
    doctorId: "doc00-7",
    doctorName: "Dr. Ganesh",
    speciality: "Endocrinology",
    noOfYearsExperience: 20,
    imgUrl: "/images/doc7.jpg",
  },
  {
    doctorId: "doc00-8",
    doctorName: "Dr. Gauri",
    speciality: "Urology",
    noOfYearsExperience: 3,
    imgUrl: "/images/doc8.jpg",
  },
  {
    doctorId: "doc00-9",
    doctorName: "Dr. Harsh",
    speciality: "Cardiology",
    noOfYearsExperience: 10,
    imgUrl: "/images/doc9.jpg",
  },
  {
    doctorId: "doc00-10",
    doctorName: "Dr. Ishita",
    speciality: "Neurology",
    noOfYearsExperience: 4,
    imgUrl: "/images/doc10.jpg",
  },
  {
    doctorId: "doc00-11",
    doctorName: "Dr. Jeevan",
    speciality: "Pediatrics",
    noOfYearsExperience: 16,
    imgUrl: "/images/doc11.jpg",
  },
  {
    doctorId: "doc00-12",
    doctorName: "Dr. Jyoti",
    speciality: "Orthopedics",
    noOfYearsExperience: 9,
    imgUrl: "/images/doc12.jpg",
  },
  {
    doctorId: "doc00-13",
    doctorName: "Dr. Kavi",
    speciality: "Dermatology",
    noOfYearsExperience: 7,
    imgUrl: "/images/doc13.jpg",
  },
  {
    doctorId: "doc00-14",
    doctorName: "Dr. Kriti",
    speciality: "Psychiatry",
    noOfYearsExperience: 14,
    imgUrl: "/images/doc14.jpg",
  },
  {
    doctorId: "doc00-15",
    doctorName: "Dr. Lalita",
    speciality: "Endocrinology",
    noOfYearsExperience: 18,
    imgUrl: "/images/doc15.jpg",
  },
  {
    doctorId: "doc00-16",
    doctorName: "Dr. Mahesh",
    speciality: "Urology",
    noOfYearsExperience: 6,
    imgUrl: "/images/doc16.jpg",
  },
  {
    doctorId: "doc00-17",
    doctorName: "Dr. Prekshya",
    speciality: "Cardiology",
    noOfYearsExperience: 14,
    imgUrl: "/images/doc17.jpeg",
  },
  {
    doctorId: "doc00-18",
    doctorName: "Dr. Bishal",
    speciality: "Neurology",
    noOfYearsExperience: 2,
    imgUrl: "/images/doc18.jpg",
  },
  {
    doctorId: "doc00-19",
    doctorName: "Dr. Neha",
    speciality: "Endocrinology",
    noOfYearsExperience: 19,
    imgUrl: "/images/doc19.jpg",
  },
  {
    doctorId: "doc00-20",
    doctorName: "Dr. Aashish",
    speciality: "Urology",
    noOfYearsExperience: 1,
    imgUrl: "/images/doc20.jpg",
  },
];

module.exports = doctors;
